AllCops: 
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - 'test/dummy/**/*'
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  
Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Naming/FileName:
  Enabled: false