language: ruby
services:
  - mysql

rvm:
  - 2.4.0

before_script:
  - bundle install
  - RAILS_ENV=test bundle exec rails db:create
  - RAILS_ENV=test bundle exec rails db:migrate

script: bundle exec rake test
